global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'moviebooking_metric'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.1.7:8080']